# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=2000)),
                ('sent', models.DateTimeField(verbose_name='Sent On')),
            ],
        ),
    ]
